// Mock assignments data
export const mockAssignments = [
  {
    _id: 'assignment1',
    id: 'assignment1',
    title: 'Programming Project 1',
    description: 'Create a simple calculator application using Python. Include basic arithmetic operations.',
    courseId: 'course1',
    courseName: 'Introduction to Computer Science',
    courseCode: 'CS101',
    instructorId: 'teacher1',
    instructor: 'Dr. Sarah Johnson',
    dueDate: '2024-02-15T23:59:59Z',
    maxScore: 100,
    createdAt: '2024-01-20T00:00:00Z',
    attachments: [
      {
        id: 'assignment1_file1',
        name: 'project-brief.pdf',
        type: 'application/pdf',
        size: 245760,
        url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      },
      {
        id: 'assignment1_file2',
        name: 'sample-ui.png',
        type: 'image/png',
        size: 153600,
        url: 'https://images.unsplash.com/photo-1587620962725-abab7fe55159?auto=format&fit=crop&w=800&q=60',
      },
    ],
    submissions: [
      {
        studentId: 'student1',
        studentName: 'Alice Williams',
        attachments: [
          {
            id: 'assignment1_submission_student1',
            name: 'calculator-solution.pdf',
            type: 'application/pdf',
            size: 204800,
            url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
          },
        ],
        notes: 'Source code and report attached as PDF.',
        submittedAt: '2024-02-14T10:30:00Z',
        score: null,
        graded: false,
      },
      {
        studentId: 'student2',
        studentName: 'Bob Martinez',
        attachments: [
          {
            id: 'assignment1_submission_student2',
            name: 'bob-calculator.pdf',
            type: 'application/pdf',
            size: 256000,
            url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
          },
        ],
        notes: 'Includes documentation and screenshots.',
        submittedAt: '2024-02-13T15:20:00Z',
        score: 85,
        graded: true,
      },
    ],
  },
  {
    _id: 'assignment2',
    id: 'assignment2',
    title: 'Calculus Problem Set 1',
    description: 'Solve problems 1-10 from Chapter 3. Show all work and submit as PDF.',
    courseId: 'course2',
    courseName: 'Calculus I',
    courseCode: 'MATH101',
    instructorId: 'teacher2',
    instructor: 'Prof. Michael Chen',
    dueDate: '2024-02-10T23:59:59Z',
    maxScore: 50,
    createdAt: '2024-01-18T00:00:00Z',
    attachments: [
      {
        id: 'assignment2_file1',
        name: 'problem-set.pdf',
        type: 'application/pdf',
        size: 196608,
        url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      },
    ],
    submissions: [
      {
        studentId: 'student1',
        studentName: 'Alice Williams',
        attachments: [
          {
            id: 'assignment2_submission_student1',
            name: 'calculus-solutions.pdf',
            type: 'application/pdf',
            size: 225280,
            url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
          },
        ],
        notes: 'Completed solutions with all work shown.',
        submittedAt: '2024-02-09T20:00:00Z',
        score: 48,
        graded: true,
      },
    ],
  },
  {
    _id: 'assignment3',
    id: 'assignment3',
    title: 'Data Structures Implementation',
    description: 'Implement a binary search tree with insert, delete, and search operations.',
    courseId: 'course3',
    courseName: 'Data Structures and Algorithms',
    courseCode: 'CS201',
    instructorId: 'teacher1',
    instructor: 'Dr. Sarah Johnson',
    dueDate: '2024-02-20T23:59:59Z',
    maxScore: 100,
    createdAt: '2024-01-22T00:00:00Z',
    attachments: [
      {
        id: 'assignment3_file1',
        name: 'bst-guide.pdf',
        type: 'application/pdf',
        size: 167936,
        url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      },
      {
        id: 'assignment3_file2',
        name: 'performance-chart.png',
        type: 'image/png',
        size: 143360,
        url: 'https://images.unsplash.com/photo-1483478550801-ceba5fe50e8e?auto=format&fit=crop&w=800&q=60',
      },
    ],
    submissions: [],
  },
  {
    _id: 'assignment4',
    id: 'assignment4',
    title: 'Database Design Project',
    description: 'Design a database schema for a library management system. Include ER diagram and SQL scripts.',
    courseId: 'course4',
    courseName: 'Database Systems',
    courseCode: 'CS301',
    instructorId: 'teacher1',
    instructor: 'Dr. Sarah Johnson',
    dueDate: '2024-02-25T23:59:59Z',
    maxScore: 150,
    createdAt: '2024-01-25T00:00:00Z',
    attachments: [
      {
        id: 'assignment4_file1',
        name: 'database-requirements.pdf',
        type: 'application/pdf',
        size: 212992,
        url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      },
      {
        id: 'assignment4_file2',
        name: 'er-diagram.png',
        type: 'image/png',
        size: 184320,
        url: 'https://images.unsplash.com/photo-1517430816045-df4b7de27e86?auto=format&fit=crop&w=800&q=60',
      },
    ],
    submissions: [],
  },
];

