// Mock lost & found data
export const mockLostFound = [
  {
    _id: 'lostfound1',
    id: 'lostfound1',
    title: 'Lost iPhone 12',
    description: 'Black iPhone 12 with a blue case. Lost near the library on January 15th. Has a sticker on the back.',
    type: 'lost',
    location: 'Library - 2nd Floor',
    date: '2024-01-15T10:00:00Z',
    reportedBy: 'student1',
    reportedByName: 'Alice Williams',
    verified: false,
    status: 'pending',
    createdAt: '2024-01-15T10:30:00Z',
    attachments: [
      {
        id: 'lostfound1_attachment1',
        name: 'iphone-photo.png',
        type: 'image/png',
        size: 245678,
        url: 'https://images.unsplash.com/photo-1512495964-43b4e58c0c13?auto=format&fit=crop&w=900&q=60',
      },
      {
        id: 'lostfound1_attachment2',
        name: 'serial-number.pdf',
        type: 'application/pdf',
        size: 106496,
        url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      },
    ],
  },
  {
    _id: 'lostfound2',
    id: 'lostfound2',
    title: 'Found Laptop Bag',
    description: 'Black laptop bag found in the cafeteria. Contains a MacBook Pro and charger. Please contact to claim.',
    type: 'found',
    location: 'Cafeteria - Main Hall',
    date: '2024-01-16T14:00:00Z',
    reportedBy: 'student2',
    reportedByName: 'Bob Martinez',
    verified: true,
    status: 'approved',
    createdAt: '2024-01-16T14:20:00Z',
    attachments: [
      {
        id: 'lostfound2_attachment1',
        name: 'bag-photo.jpg',
        type: 'image/jpeg',
        size: 312876,
        url: 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=900&q=60',
      },
    ],
  },
  {
    _id: 'lostfound3',
    id: 'lostfound3',
    title: 'Lost Wallet',
    description: 'Brown leather wallet containing ID and credit cards. Lost near the sports complex.',
    type: 'lost',
    location: 'Sports Complex',
    date: '2024-01-17T16:00:00Z',
    reportedBy: 'student3',
    reportedByName: 'Emma Davis',
    verified: false,
    status: 'pending',
    createdAt: '2024-01-17T16:15:00Z',
    attachments: [],
  },
  {
    _id: 'lostfound4',
    id: 'lostfound4',
    title: 'Found Keys',
    description: 'Set of keys with a keychain found in the parking lot. Includes car keys and house keys.',
    type: 'found',
    location: 'Parking Lot - Section B',
    date: '2024-01-18T08:00:00Z',
    reportedBy: 'teacher1',
    reportedByName: 'Dr. Sarah Johnson',
    verified: true,
    status: 'approved',
    createdAt: '2024-01-18T08:30:00Z',
    attachments: [
      {
        id: 'lostfound4_attachment1',
        name: 'keys.png',
        type: 'image/png',
        size: 187452,
        url: 'https://images.unsplash.com/photo-1521218108076-c5fb47cfd6d5?auto=format&fit=crop&w=900&q=60',
      },
    ],
  },
  {
    _id: 'lostfound5',
    id: 'lostfound5',
    title: 'Lost Watch',
    description: 'Silver wristwatch, brand: Casio. Lost during the sports day event.',
    type: 'lost',
    location: 'Sports Field',
    date: '2024-01-19T12:00:00Z',
    reportedBy: 'student1',
    reportedByName: 'Alice Williams',
    verified: false,
    attachments: [
      {
        id: 'lostfound5_attachment1',
        name: 'watch.jpg',
        type: 'image/jpeg',
        size: 204812,
        url: 'https://images.unsplash.com/photo-1518544801958-efcbf8a7ec10?auto=format&fit=crop&w=900&q=60',
      },
    ],
    status: 'pending',
    createdAt: '2024-01-19T12:45:00Z',
  },
];

