// Mock notices data
export const mockNotices = [
  {
    _id: 'notice1',
    id: 'notice1',
    title: 'Welcome Back to Campus!',
    content: 'We are excited to welcome all students back to campus for the new academic year. Please ensure you have completed all registration requirements.',
    author: 'Dr. Sarah Johnson',
    authorId: 'teacher1',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
    priority: 'high',
  },
  {
    _id: 'notice2',
    id: 'notice2',
    title: 'Library Hours Extended',
    content: 'The library will now be open until 10 PM on weekdays. Study rooms are available for booking through the online portal.',
    author: 'Library Administration',
    authorId: 'admin1',
    createdAt: '2024-01-16T09:00:00Z',
    updatedAt: '2024-01-16T09:00:00Z',
    priority: 'medium',
  },
  {
    _id: 'notice3',
    id: 'notice3',
    title: 'Assignment Submission Deadline',
    content: 'Reminder: All assignments for CS101 are due by Friday, January 20th at 11:59 PM. Late submissions will not be accepted.',
    author: 'Prof. Michael Chen',
    authorId: 'teacher2',
    createdAt: '2024-01-17T14:00:00Z',
    updatedAt: '2024-01-17T14:00:00Z',
    priority: 'high',
  },
  {
    _id: 'notice4',
    id: 'notice4',
    title: 'Sports Day Registration Open',
    content: 'Annual Sports Day is scheduled for February 15th. Registration is now open. Please register by January 30th.',
    author: 'Sports Committee',
    authorId: 'admin1',
    createdAt: '2024-01-18T11:00:00Z',
    updatedAt: '2024-01-18T11:00:00Z',
    priority: 'medium',
  },
  {
    _id: 'notice5',
    id: 'notice5',
    title: 'Cafeteria Menu Update',
    content: 'New healthy meal options have been added to the cafeteria menu. Check the updated menu on our website.',
    author: 'Cafeteria Management',
    authorId: 'admin1',
    createdAt: '2024-01-19T08:00:00Z',
    updatedAt: '2024-01-19T08:00:00Z',
    priority: 'low',
  },
];

