// Mock users data
// Note: This file is used by the mock API system
// For login credentials, see src/data/mockUsers.js

export const mockUsers = [
  {
    _id: 'admin1',
    id: 'admin1',
    name: 'John Admin',
    email: 'admin@campus.edu',
    password: 'admin123',
    role: 'admin',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    _id: 'teacher1',
    id: 'teacher1',
    name: 'Dr. Sarah Johnson',
    email: 'sarah.johnson@campus.edu',
    password: 'teacher123',
    role: 'teacher',
    department: 'Computer Science',
    createdAt: '2024-01-02T00:00:00Z',
  },
  {
    _id: 'teacher2',
    id: 'teacher2',
    name: 'Prof. Michael Chen',
    email: 'michael.chen@campus.edu',
    password: 'teacher123',
    role: 'teacher',
    department: 'Mathematics',
    createdAt: '2024-01-03T00:00:00Z',
  },
  {
    _id: 'student1',
    id: 'student1',
    name: 'Alice Williams',
    email: 'alice.williams@campus.edu',
    password: 'student123',
    role: 'student',
    studentId: 'STU001',
    batch: '2024',
    createdAt: '2024-01-04T00:00:00Z',
  },
  {
    _id: 'student2',
    id: 'student2',
    name: 'Bob Martinez',
    email: 'bob.martinez@campus.edu',
    password: 'student123',
    role: 'student',
    studentId: 'STU002',
    batch: '2024',
    createdAt: '2024-01-05T00:00:00Z',
  },
  {
    _id: 'student3',
    id: 'student3',
    name: 'Emma Davis',
    email: 'emma.davis@campus.edu',
    password: 'student123',
    role: 'student',
    studentId: 'STU003',
    batch: '2023',
    createdAt: '2024-01-06T00:00:00Z',
  },
  {
    _id: 'cr1',
    id: 'cr1',
    name: 'David Brown',
    email: 'david.brown@campus.edu',
    password: 'cr123',
    role: 'cr',
    studentId: 'STU004',
    batch: '2024',
    createdAt: '2024-01-07T00:00:00Z',
  },
  {
    _id: 'cr2',
    id: 'cr2',
    name: 'Sophia Lee',
    email: 'sophia.lee@campus.edu',
    password: 'cr123',
    role: 'cr',
    studentId: 'STU005',
    batch: '2023',
    createdAt: '2024-01-08T00:00:00Z',
  },
  {
    _id: 'alumni1',
    id: 'alumni1',
    name: 'Robert Taylor',
    email: 'robert.taylor@alumni.campus.edu',
    password: 'alumni123',
    role: 'alumni',
    batch: '2020',
    createdAt: '2024-01-09T00:00:00Z',
  },
  {
    _id: 'alumni2',
    id: 'alumni2',
    name: 'Lisa Anderson',
    email: 'lisa.anderson@alumni.campus.edu',
    password: 'alumni123',
    role: 'alumni',
    batch: '2019',
    createdAt: '2024-01-10T00:00:00Z',
  },
  {
    _id: 'alumni3',
    id: 'alumni3',
    name: 'James Wilson',
    email: 'james.wilson@alumni.campus.edu',
    password: 'alumni123',
    role: 'alumni',
    batch: '2021',
    createdAt: '2024-01-11T00:00:00Z',
  },
];

